"""
Market Fix — Built-in база из 50 заведений Алматы.

Данные собраны из открытых источников (2ГИС, Tripadvisor, Restolife, Restoran.kz,
официальные сайты) по состоянию на 8 августа 2026 года.

Каждое заведение — словарь со стандартизированными полями для AI-подбора.
Для неизвестных значений используется None (не интерпретируется как «нет»).
"""

from __future__ import annotations
from typing import Any

LAST_VERIFIED_AT = "2026-08-08"


def _v(
    venue_id: str,
    name: str,
    category: str,
    subcategory: str,
    cuisines: list[str],
    price_segment: str,
    average_check: int | None,
    district: str,
    address: str,
    best_for: list[str],
    atmosphere: list[str],
    ai_score: int,
    confidence: str,
    **extra: Any,
) -> dict[str, Any]:
    """Построить стандартную карточку заведения."""
    base: dict[str, Any] = {
        "venue_id": venue_id,
        "name": name,
        "category": category,
        "subcategory": subcategory,
        "cuisines": cuisines,
        "price_segment": price_segment,
        "average_check": average_check,
        "district": district,
        "address": address,
        "best_for": best_for,
        "atmosphere": atmosphere,
        "ai_score": ai_score,
        "confidence": confidence,
        "verification_status": "partially_verified",
        "last_verified_at": LAST_VERIFIED_AT,
    }
    base.update(extra)
    return base


# Оценки сценариев 0–5 (0 — не подходит, 5 — одно из лучших применений).
# Ключи соответствуют типовым запросам AI-подбора.
SCENARIO_KEYS = [
    "date",
    "family",
    "business",
    "friends",
    "birthday",
    "banquet",
    "corporate",
    "tourist",
    "laptop",
    "large_group",
]

SCENARIO_LABELS = {
    "date": "Свидание",
    "family": "Семейный ужин",
    "business": "Деловая встреча",
    "friends": "Встреча с друзьями",
    "birthday": "День рождения",
    "banquet": "Банкет",
    "corporate": "Корпоратив",
    "tourist": "Туристический визит",
    "laptop": "Работа с ноутбуком",
    "large_group": "Большая компания",
}

VENUES: list[dict[str, Any]] = [
    # ---- 1. Премиальный сегмент / fine dining ----
    _v(
        "ALM-001", "Nuala", "Ресторан", "Fine dining",
        ["Авторская", "Европейская", "Морепродукты"], "premium", 20000,
        "Алмалинский", "ул. Богенбай батыра, 134",
        ["Свидание", "Премиальный ужин", "Туристический визит"],
        ["Тихая", "Романтичная", "Премиальная", "С красивым интерьером"],
        88, "Средняя",
        rating_2gis=4.7, reviews_2gis=1022,
        phone="+7 700 111 60 36", website="http://sologroup.kz/nuala",
        two_gis_url="https://2gis.kz/almaty/firm/70000001060271664",
        working_hours="Вс–Чт: 11:00–00:00; Пт–Сб: 11:00–01:00",
        breakfast=True, brunch=True, terrace=True, wine_card=True,
        booking_available=True, booking_method="website",
        scenarios={"date": 5, "business": 4, "family": 2, "friends": 3,
                   "birthday": 4, "banquet": 3, "corporate": 3, "tourist": 5,
                   "laptop": 1, "large_group": 2},
        pros=["Премиальная авторская кухня", "Винная карта", "Завтраки и brunch",
              "Высокий рейтинг 2ГИС", "Туристическая привлекательность"],
        cons=["Высокий средний чек", "Wi-Fi и парковка требуют проверки"],
        popularity_level="Очень высокая",
        data_completeness="Высокая",
    ),
    _v(
        "ALM-008", "Sandyq", "Ресторан", "National premium",
        ["Казахская"], "upper_mid", None,
        "Алмалинский", "проспект Абылай хана, 55",
        ["Туристический визит", "Семейный ужин", "Деловая встреча"],
        ["Премиальная", "Семейная", "С красивым интерьером"],
        87, "Средняя",
        halal=True, wifi=True, terrace=True, vip_room=True, kids_room=True,
        live_music=True, takeaway=True, booking_available=True,
        working_hours="Ежедневно 12:00–00:00",
        two_gis_url="https://2gis.kz/almaty/firm/70000001057699052",
        phone="+7 775 007 …",
        scenarios={"date": 3, "business": 4, "family": 5, "friends": 4,
                   "birthday": 4, "banquet": 4, "corporate": 4, "tourist": 5,
                   "laptop": 1, "large_group": 5},
        pros=["Halal-кухня", "VIP-зал", "Летняя веранда", "Детская комната",
              "Живая музыка", "Wi-Fi"],
        cons=["Средний чек не подтверждён", "Вместимость требует сверки"],
        popularity_level="Очень высокая",
        data_completeness="Средняя",
    ),
    _v(
        "ALM-026", "Auyl Cafe", "Ресторан", "National concept",
        ["Казахская", "Центральноазиатская"], "upper_mid", 20000,
        "Медеуский", "ул. Керей-Жанибек хандар, 586",
        ["Туристический визит", "Свидание", "Особый ужин"],
        ["Современная", "Премиальная"],
        87, "Средняя",
        rating_2gis=None, booking_available=True, takeaway=True,
        working_hours="Ежедневно 11:00–00:00",
        two_gis_url="https://2gis.kz/almaty/firm/70000001067620756",
        phone="+7 705 586 …",
        scenarios={"date": 4, "business": 3, "family": 4, "friends": 4,
                   "birthday": 3, "banquet": 2, "corporate": 2, "tourist": 5,
                   "laptop": 1, "large_group": 3},
        pros=["Международное признание (50 Best Discovery)", "Национальная кухня",
              "Подтверждённый средний чек 20 000 ₸"],
        cons=["Адрес в удалённой части города", "Wi-Fi и парковка не подтверждены"],
        popularity_level="Очень высокая",
        data_completeness="Средняя",
    ),
    _v(
        "ALM-027", "Сё-Сё", "Ресторан", "Contemporary dining",
        ["Авторская", "Современная"], "premium", None,
        "Не найдено", "Не найдено",
        ["Гастрономический опыт", "Свидание", "Special occasion"],
        ["Современная", "Камерная", "Премиальная"],
        86, "Средняя",
        scenarios={"date": 5, "business": 4, "family": 2, "friends": 3,
                   "birthday": 4, "banquet": 2, "corporate": 3, "tourist": 4,
                   "laptop": 1, "large_group": 2},
        pros=["Международное признание (50 Best Discovery)", "Авторская кухня",
              "Уникальный гастрономический опыт"],
        cons=["Адрес и контакты требуют проверки", "Высокий ценовой сегмент"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-029", "Yellow Door", "Бар", "Cocktail bar",
        ["Коктейли", "Bar food"], "premium", None,
        "Не найдено", "Не найдено",
        ["Свидание", "Коктейли", "Вечерняя встреча"],
        ["Тусовочное", "Современное", "Премиальная"],
        85, "Средняя",
        scenarios={"date": 5, "business": 2, "family": 1, "friends": 5,
                   "birthday": 3, "banquet": 1, "corporate": 1, "tourist": 4,
                   "laptop": 0, "large_group": 2},
        pros=["Международное признание (50 Best Discovery)", "Авторские коктейли",
              "Атмосферный вечер"],
        cons=["Возможны возрастные ограничения", "Адрес требует проверки"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-030", "French 42", "Бар", "Cocktail bar",
        ["Коктейли", "Bar food"], "premium", None,
        "Не найдено", "Не найдено",
        ["Свидание", "Nightlife", "Private evening"],
        ["Тусовочное", "Современное"],
        85, "Средняя",
        scenarios={"date": 5, "business": 2, "family": 1, "friends": 5,
                   "birthday": 3, "banquet": 1, "corporate": 1, "tourist": 4,
                   "laptop": 0, "large_group": 2},
        pros=["Международное признание (50 Best Discovery)", "Авторские коктейли"],
        cons=["График и адрес требуют проверки", "Премиальный сегмент"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-011", "Seven Bar and Restaurant", "Ресторан", "Premium restaurant / bar",
        ["Европейская", "Steakhouse"], "premium", None,
        "Не найдено", "Не найдено",
        ["Свидание", "Деловой ужин", "Вечер"],
        ["Премиальная", "Современная"],
        84, "Средняя",
        scenarios={"date": 5, "business": 5, "family": 2, "friends": 4,
                   "birthday": 4, "banquet": 3, "corporate": 3, "tourist": 3,
                   "laptop": 1, "large_group": 3},
        pros=["Премиальный steakhouse", "Подходит для деловых ужинов"],
        cons=["Адрес и контакты требуют проверки"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-012", "La Barca Fish & Wine", "Ресторан", "Seafood / wine bar",
        ["Морепродукты", "Рыба"], "premium", None,
        "Не найдено", "Не найдено",
        ["Свидание", "Деловой ужин"],
        ["Тихая", "Премиальная"],
        84, "Низкая",
        scenarios={"date": 5, "business": 4, "family": 2, "friends": 3,
                   "birthday": 3, "banquet": 2, "corporate": 2, "tourist": 3,
                   "laptop": 1, "large_group": 2},
        pros=["Уникальная seafood-специализация", "Винная карта"],
        cons=["Данные требуют верификации"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-013", "INZHU", "Ресторан", "Premium dining",
        ["Европейская", "Средиземноморская"], "premium", None,
        "Не найдено", "Не найдено",
        ["Свидание", "Special occasion"],
        ["Премиальная", "С красивым интерьером"],
        81, "Средняя",
        scenarios={"date": 5, "business": 4, "family": 2, "friends": 3,
                   "birthday": 4, "banquet": 2, "corporate": 2, "tourist": 3,
                   "laptop": 1, "large_group": 2},
        pros=["Премиальный интерьер", "Гастрономический сценарий"],
        cons=["Контакты требуют проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-032", "Villa Dei Fiori", "Ресторан", "Italian premium",
        ["Итальянская"], "premium", None,
        "Не найдено", "Не найдено",
        ["Свидание", "Деловой ужин"],
        ["Романтичная", "Премиальная"],
        81, "Низкая",
        scenarios={"date": 5, "business": 4, "family": 3, "friends": 3,
                   "birthday": 3, "banquet": 2, "corporate": 2, "tourist": 2,
                   "laptop": 1, "large_group": 2},
        pros=["Премиальная итальянская кухня"],
        cons=["Данные требуют верификации"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-043", "MORE & MORE", "Ресторан", "Premium restaurant",
        ["Авторская", "Международная"], "premium", None,
        "Не найдено", "Не найдено",
        ["Свидание", "Вечерний ужин"],
        ["Премиальная", "Современная"],
        72, "Низкая",
        scenarios={"date": 4, "business": 3, "family": 2, "friends": 3,
                   "birthday": 3, "banquet": 2, "corporate": 2, "tourist": 2,
                   "laptop": 1, "large_group": 2},
        pros=["Высокий средний чек", "Премиальный сценарий"],
        cons=["Депозит и контакты требуют проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-050", "Churchill Bar", "Бар", "Cocktail / steak bar",
        ["Коктейли", "Стейки", "Bar food"], "premium", None,
        "Не найдено", "Не найдено",
        ["Свидание", "Деловая встреча", "Nightlife"],
        ["Премиальная", "Современная"],
        69, "Низкая",
        scenarios={"date": 4, "business": 4, "family": 1, "friends": 4,
                   "birthday": 3, "banquet": 1, "corporate": 2, "tourist": 3,
                   "laptop": 0, "large_group": 2},
        pros=["Premium nightlife-сегмент", "Стейки и коктейли"],
        cons=["Данные требуют верификации"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),

    # ---- 2. National / Central Asian ----
    _v(
        "ALM-004", "Daredzhani Kunayeva", "Ресторан", "National restaurant",
        ["Грузинская"], "mid", None,
        "Медеуский", "ул. Кунаева, 85",
        ["Семья", "Друзья", "Большая компания"],
        ["Семейная", "Уютная"],
        83, "Высокая",
        business_lunch=True, wine_card=True, kids_menu=True, vip_room=True,
        live_music=True, takeaway=True, booking_available=True, capacity=90,
        working_hours="Ежедневно 10:00–00:00",
        two_gis_url="https://2gis.kz/almaty/firm/9429940000957502",
        phone="+7 771 722 …",
        scenarios={"date": 3, "business": 3, "family": 5, "friends": 5,
                   "birthday": 4, "banquet": 3, "corporate": 3, "tourist": 4,
                   "laptop": 1, "large_group": 5},
        pros=["Грузинская кухня", "Бизнес-ланч 12:00–16:00", "Вместимость до 90 мест",
              "Детское меню", "VIP-зал", "Живая музыка"],
        cons=["Средний чек не подтверждён", "Парковка и Wi-Fi требуют проверки"],
        popularity_level="Высокая",
        data_completeness="Высокая",
    ),
    _v(
        "ALM-035", "Daredzhani Kurmangazy", "Ресторан", "National restaurant",
        ["Грузинская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Семья", "Друзья", "Ужин"],
        ["Семейная", "Уютная"],
        73, "Средняя",
        takeaway=True, booking_available=True,
        scenarios={"date": 3, "business": 3, "family": 5, "friends": 5,
                   "birthday": 4, "banquet": 3, "corporate": 3, "tourist": 3,
                   "laptop": 1, "large_group": 4},
        pros=["Грузинская кухня", "Отдельный филиал (не смешивать с Kunayeva)"],
        cons=["Адрес конкретного филиала требует проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-006", "Tyubeteika", "Ресторан", "National dining",
        ["Узбекская", "Центральноазиатская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Туристический визит", "Семья", "Группы"],
        ["Семейная", "Традиционная"],
        82, "Высокая",
        scenarios={"date": 2, "business": 2, "family": 5, "friends": 4,
                   "birthday": 4, "banquet": 4, "corporate": 3, "tourist": 5,
                   "laptop": 1, "large_group": 5},
        pros=["Большой объём отзывов", "Узбекская и центральноазиатская кухня",
              "Туристический сценарий"],
        cons=["Адрес и контакты требуют проверки"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-020", "Alasha", "Ресторан", "Show restaurant",
        ["Узбекская", "Центральноазиатская"], "premium", None,
        "Не найдено", "Не найдено",
        ["Банкет", "Свадьба", "Туристический визит"],
        ["Шоу-программа", "Премиальная"],
        82, "Средняя",
        banquet_available=True, terrace=True, booking_available=True,
        scenarios={"date": 3, "business": 3, "family": 4, "friends": 4,
                   "birthday": 5, "banquet": 5, "corporate": 5, "tourist": 5,
                   "laptop": 0, "large_group": 5},
        pros=["Show-формат", "Банкетные сценарии", "Терраса"],
        cons=["Адрес и депозит требуют проверки"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-009", "Navat", "Ресторан", "Casual national",
        ["Центральноазиатская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Семья", "Туристы", "Повседневный ужин"],
        ["Семейная", "Casual"],
        78, "Средняя",
        booking_available=True,
        scenarios={"date": 2, "business": 2, "family": 5, "friends": 4,
                   "birthday": 3, "banquet": 3, "corporate": 3, "tourist": 4,
                   "laptop": 1, "large_group": 5},
        pros=["Узнаваемый бренд", "Доступный сегмент", "Национальная кухня"],
        cons=["Адрес конкретного филиала требует проверки"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-015", "Kazakh Restaurant Abay", "Ресторан", "National / barbecue",
        ["Казахская", "Мясная"], "upper_mid", None,
        "Не найдено", "Не найдено",
        ["Большая компания", "Туристы", "Ужин"],
        ["Традиционная", "Семейная"],
        73, "Средняя",
        banquet_available=True,
        scenarios={"date": 2, "business": 2, "family": 4, "friends": 4,
                   "birthday": 3, "banquet": 4, "corporate": 3, "tourist": 4,
                   "laptop": 1, "large_group": 5},
        pros=["Казахская кухня и мясо", "Банкет"],
        cons=["Адрес и вместимость требуют проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-041", "Саксаул", "Ресторан", "National restaurant",
        ["Центральноазиатская"], "upper_mid", None,
        "Не найдено", "Не найдено",
        ["Национальная кухня", "Туристы", "Группы"],
        ["Традиционная", "Семейная"],
        75, "Средняя",
        banquet_available=True,
        scenarios={"date": 2, "business": 2, "family": 4, "friends": 4,
                   "birthday": 3, "banquet": 4, "corporate": 3, "tourist": 4,
                   "laptop": 1, "large_group": 5},
        pros=["Известное заведение национальной кухни"],
        cons=["Адрес требует проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-014", "Bosphorus Restaurant", "Ресторан", "National restaurant",
        ["Турецкая"], "upper_mid", None,
        "Не найдено", "Не найдено",
        ["Семья", "Друзья", "Туристы"],
        ["Семейная", "Уютная"],
        80, "Средняя",
        kids_menu=None,
        scenarios={"date": 3, "business": 3, "family": 5, "friends": 4,
                   "birthday": 3, "banquet": 3, "corporate": 3, "tourist": 4,
                   "laptop": 1, "large_group": 4},
        pros=["Турецкая кухня", "Семейный сценарий"],
        cons=["Детские опции требуют проверки"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),

    # ---- 3. Casual / массовый сегмент ----
    _v(
        "ALM-002", "Beefeater Dostyk", "Ресторан", "Steakhouse / bar",
        ["Европейская", "Стейки"], "upper_mid", None,
        "Не найдено", "Не найдено",
        ["Друзья", "Деловая встреча", "День рождения"],
        ["Премиальная", "Современная"],
        84, "Высокая",
        booking_available=True,
        scenarios={"date": 4, "business": 5, "family": 3, "friends": 5,
                   "birthday": 5, "banquet": 3, "corporate": 4, "tourist": 3,
                   "laptop": 1, "large_group": 4},
        pros=["Высокий рейтинг и большой объём отзывов", "Steakhouse-специализация",
              "Универсальные сценарии"],
        cons=["Адрес конкретного филиала требует проверки"],
        popularity_level="Очень высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-022", "Beefeater Samal", "Ресторан", "Restaurant / wine bar",
        ["Европейская"], "upper_mid", None,
        "Не найдено", "Не найдено",
        ["Свидание", "Деловой ужин", "Вечер"],
        ["Премиальная", "Уютная"],
        79, "Средняя",
        booking_available=True,
        scenarios={"date": 4, "business": 4, "family": 3, "friends": 4,
                   "birthday": 3, "banquet": 2, "corporate": 3, "tourist": 2,
                   "laptop": 1, "large_group": 3},
        pros=["Отдельный филиал Beefeater", "Винная карта"],
        cons=["График требует проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-003", "Chechil Rozybakiyeva", "Паб", "Casual dining / pub",
        ["Европейская", "Американская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Друзья", "День рождения", "Поздний ужин"],
        ["Шумное", "Тусовочное", "Casual"],
        83, "Высокая",
        scenarios={"date": 2, "business": 1, "family": 2, "friends": 5,
                   "birthday": 4, "banquet": 2, "corporate": 2, "tourist": 2,
                   "laptop": 1, "large_group": 5},
        pros=["Высокая узнаваемость", "Большой объём отзывов",
              "Демократичный сегмент"],
        cons=["Не подходит для тихих сценариев"],
        popularity_level="Очень высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-036", "Chechil Forum", "Паб", "Pub / live music",
        ["Европейская", "Американская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Большая компания", "Live music"],
        ["Шумное", "Тусовочное"],
        74, "Средняя",
        live_music=True,
        scenarios={"date": 2, "business": 1, "family": 2, "friends": 5,
                   "birthday": 4, "banquet": 2, "corporate": 2, "tourist": 2,
                   "laptop": 1, "large_group": 5},
        pros=["Live music", "Отдельный филиал (не смешивать с Rozybakiyeva)"],
        cons=["График требует проверки"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-037", "Chechil 4mkrn", "Паб", "Casual pub",
        ["Европейская", "Американская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Друзья", "Поздний ужин"],
        ["Шумное", "Casual"],
        73, "Низкая",
        scenarios={"date": 2, "business": 1, "family": 2, "friends": 5,
                   "birthday": 3, "banquet": 2, "corporate": 2, "tourist": 1,
                   "laptop": 1, "large_group": 4},
        pros=["Отдельный филиал сети Chechil", "Локальный спрос"],
        cons=["Адрес требует проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-016", "KetchUp", "Ресторан", "Fast casual",
        ["Бургеры", "Американская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Друзья", "Семья", "Быстрый обед"],
        ["Casual", "Современное"],
        77, "Средняя",
        delivery=True,
        scenarios={"date": 2, "business": 1, "family": 4, "friends": 5,
                   "birthday": 3, "banquet": 1, "corporate": 1, "tourist": 1,
                   "laptop": 2, "large_group": 3},
        pros=["Высокий рейтинг", "Доставка", "Массовый casual-сегмент"],
        cons=["Не подходит для деловых сценариев"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-019", "Line Brew", "Ресторан", "Steakhouse / beer restaurant",
        ["Европейская", "Мясная"], "upper_mid", None,
        "Не найдено", "Не найдено",
        ["Большая компания", "Спорт", "Вечер"],
        ["Шумное", "Casual"],
        79, "Средняя",
        scenarios={"date": 2, "business": 2, "family": 3, "friends": 5,
                   "birthday": 4, "banquet": 3, "corporate": 3, "tourist": 2,
                   "laptop": 1, "large_group": 5},
        pros=["Узнаваемый формат", "Стейки и пиво", "Вместимость"],
        cons=["График конкретного филиала требует проверки"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-017", "Mapache Bar — Steak & Burger", "Бар", "Steakhouse / burger bar",
        ["Американская", "Мясная"], "upper_mid", None,
        "Не найдено", "Не найдено",
        ["Друзья", "День рождения", "Вечер"],
        ["Современное", "Casual"],
        80, "Средняя",
        booking_available=True,
        scenarios={"date": 3, "business": 2, "family": 3, "friends": 5,
                   "birthday": 4, "banquet": 2, "corporate": 2, "tourist": 2,
                   "laptop": 1, "large_group": 4},
        pros=["Высокий рейтинг", "Стейки и бургеры"],
        cons=["Адрес требует проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),

    # ---- 4. Японская кухня ----
    _v(
        "ALM-005", "Manga Sushi", "Ресторан", "Sushi / delivery",
        ["Японская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Доставка", "Семья", "Друзья"],
        ["Casual", "Современное"],
        78, "Высокая",
        delivery=True, takeaway=True, booking_available=True,
        scenarios={"date": 3, "business": 1, "family": 4, "friends": 4,
                   "birthday": 3, "banquet": 1, "corporate": 1, "tourist": 2,
                   "laptop": 2, "large_group": 3},
        pros=["Высокий рейтинг", "Доставка и takeaway", "Семейный спрос"],
        cons=["Не подходит для деловых встреч"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-031", "Sumo-San", "Ресторан", "Sushi restaurant",
        ["Японская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Свидание", "Доставка", "Друзья"],
        ["Casual", "Современное"],
        80, "Средняя",
        delivery=True,
        scenarios={"date": 3, "business": 2, "family": 4, "friends": 4,
                   "birthday": 3, "banquet": 1, "corporate": 1, "tourist": 2,
                   "laptop": 2, "large_group": 3},
        pros=["Доступный японский формат", "Заметный объём отзывов"],
        cons=["Доставка требует проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-018", "Tang Ramen Bar", "Ресторан", "Ramen bar",
        ["Японская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Быстрый ужин", "Casual date", "Друзья"],
        ["Современное", "Casual"],
        79, "Средняя",
        scenarios={"date": 3, "business": 1, "family": 3, "friends": 4,
                   "birthday": 2, "banquet": 1, "corporate": 1, "tourist": 2,
                   "laptop": 2, "large_group": 2},
        pros=["Уникальный формат", "Молодёжная аудитория"],
        cons=["Малая вместимость"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),

    # ---- 5. Seafood ----
    _v(
        "ALM-007", "Ocean Basket Panfilova", "Ресторан", "Seafood restaurant",
        ["Морепродукты", "Средиземноморская"], "upper_mid", None,
        "Не найдено", "Не найдено",
        ["Семья", "Свидание", "Туристы"],
        ["Семейная", "Casual"],
        81, "Высокая",
        scenarios={"date": 4, "business": 3, "family": 5, "friends": 4,
                   "birthday": 4, "banquet": 2, "corporate": 2, "tourist": 4,
                   "laptop": 1, "large_group": 4},
        pros=["Высокий рейтинг", "Понятная seafood-специализация"],
        cons=["Парковка требует проверки"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),

    # ---- 6. Кафе / завтраки / brunch ----
    _v(
        "ALM-024", "Aroma", "Кафе", "Cafe / bakery",
        ["Европейская", "Кофе", "Выпечка"], "mid", None,
        "Не найдено", "Не найдено",
        ["Завтрак", "Кофе", "Ноутбук"],
        ["Уютная", "Тихая", "Современное"],
        75, "Средняя",
        wifi=True,
        scenarios={"date": 2, "business": 3, "family": 3, "friends": 3,
                   "birthday": 2, "banquet": 1, "corporate": 2, "tourist": 2,
                   "laptop": 5, "large_group": 1},
        pros=["Завтраки", "Кофе", "Подходит для работы с ноутбуком"],
        cons=["Не подходит для больших компаний"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-025", "Breakfast Martini", "Кафе", "Brunch cafe",
        ["Завтраки", "Brunch"], "mid", None,
        "Не найдено", "Не найдено",
        ["Завтрак", "Brunch", "Кофе"],
        ["Уютная", "Современное"],
        76, "Средняя",
        scenarios={"date": 3, "business": 2, "family": 3, "friends": 3,
                   "birthday": 2, "banquet": 1, "corporate": 1, "tourist": 2,
                   "laptop": 4, "large_group": 2},
        pros=["Завтраки и brunch", "Pet-friendly требует проверки"],
        cons=["График требует проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-038", "У Афанасича", "Кафе", "Cafe / restaurant",
        ["Европейская", "Русская"], "budget_mid", None,
        "Не найдено", "Не найдено",
        ["Завтрак", "Бизнес-ланч", "Семья"],
        ["Уютная", "Семейная"],
        74, "Средняя",
        business_lunch=True,
        scenarios={"date": 2, "business": 2, "family": 5, "friends": 3,
                   "birthday": 2, "banquet": 1, "corporate": 2, "tourist": 1,
                   "laptop": 2, "large_group": 2},
        pros=["Демократичный сегмент", "Завтраки", "Бизнес-ланч"],
        cons=["Не подходит для premium-сценариев"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-040", "Nice Restaurant", "Кафе", "Cafe / restaurant",
        ["Европейская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Завтрак", "Бизнес-ланч"],
        ["Уютная", "Casual"],
        74, "Низкая",
        business_lunch=True,
        scenarios={"date": 2, "business": 2, "family": 4, "friends": 3,
                   "birthday": 2, "banquet": 1, "corporate": 2, "tourist": 1,
                   "laptop": 3, "large_group": 2},
        pros=["Завтраки", "Бизнес-ланч", "Средний сегмент"],
        cons=["Данные требуют верификации"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),

    # ---- 7. Итальянская кухня ----
    _v(
        "ALM-033", "Parmigiano Ristorante Syrovarnya", "Ресторан", "Italian / cheese restaurant",
        ["Итальянская", "Сырная"], "upper_mid", None,
        "Не найдено", "Не найдено",
        ["Семья", "Свидание", "Ужин"],
        ["Уютная", "Современное"],
        79, "Низкая",
        booking_available=True,
        scenarios={"date": 4, "business": 3, "family": 4, "friends": 4,
                   "birthday": 3, "banquet": 2, "corporate": 2, "tourist": 2,
                   "laptop": 2, "large_group": 3},
        pros=["Уникальная сырная специализация", "Premium-casual"],
        cons=["Данные требуют верификации"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),

    # ---- 8. Индийская / вегетарианская ----
    _v(
        "ALM-021", "Tandoor", "Ресторан", "Ethnic restaurant",
        ["Индийская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Ужин", "Вегетарианский сценарий"],
        ["Уютная", "Тихая"],
        77, "Низкая",
        vegetarian=True,
        scenarios={"date": 3, "business": 2, "family": 3, "friends": 3,
                   "birthday": 2, "banquet": 1, "corporate": 1, "tourist": 3,
                   "laptop": 2, "large_group": 2},
        pros=["Индийская кухня", "Вегетарианские блюда"],
        cons=["Адрес и график требуют проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-023", "The Pakwaan", "Ресторан", "Vegetarian restaurant",
        ["Индийская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Вегетарианский и vegan-сценарий"],
        ["Уютная", "Тихая"],
        77, "Низкая",
        vegetarian=True, vegan=True,
        scenarios={"date": 2, "business": 2, "family": 3, "friends": 3,
                   "birthday": 2, "banquet": 1, "corporate": 1, "tourist": 3,
                   "laptop": 2, "large_group": 2},
        pros=["Индийская кухня", "Вегетарианская и vegan-репрезентация"],
        cons=["Данные требуют верификации"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),

    # ---- 9. Hotel / scenic dining ----
    _v(
        "ALM-010", "Vista", "Ресторан", "Hotel dining",
        ["Европейская", "Международная"], "premium", None,
        "Не найдено", "Не найдено",
        ["Завтрак", "Деловая встреча", "Туристы"],
        ["Премиальная", "Деловая"],
        76, "Низкая",
        breakfast=True, booking_available=True,
        scenarios={"date": 3, "business": 4, "family": 3, "friends": 3,
                   "birthday": 3, "banquet": 3, "corporate": 4, "tourist": 3,
                   "laptop": 3, "large_group": 3},
        pros=["Премиальный гостиничный ресторан", "Завтраки"],
        cons=["Данные требуют верификации"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-039", "Chalet", "Ресторан", "Scenic / leisure dining",
        ["Европейская"], "upper_mid", None,
        "Не найдено", "Не найдено",
        ["Отдых", "Свидание", "Туристы"],
        ["С видом", "Уютная"],
        72, "Низкая",
        terrace=True,
        scenarios={"date": 4, "business": 3, "family": 4, "friends": 4,
                   "birthday": 3, "banquet": 2, "corporate": 2, "tourist": 4,
                   "laptop": 2, "large_group": 3},
        pros=["Видовая / загородная составляющая", "Терраса"],
        cons=["Локация требует проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-042", "Turandot на Достык", "Ресторан", "Asian restaurant",
        ["Азиатская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Обед", "Деловая встреча", "Семья"],
        ["Современное", "Casual"],
        75, "Низкая",
        business_lunch=True,
        scenarios={"date": 3, "business": 3, "family": 4, "friends": 3,
                   "birthday": 2, "banquet": 2, "corporate": 2, "tourist": 2,
                   "laptop": 2, "large_group": 3},
        pros=["Центральная локация", "Завтраки и бизнес-ланч"],
        cons=["Данные требуют верификации"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-044", "Erbil", "Ресторан", "Casual restaurant",
        [], "mid", None,
        "Не найдено", "Не найдено",
        ["Повседневный ужин", "Группы"],
        ["Casual"],
        69, "Низкая",
        scenarios={"date": 2, "business": 1, "family": 3, "friends": 3,
                   "birthday": 2, "banquet": 1, "corporate": 1, "tourist": 1,
                   "laptop": 1, "large_group": 3},
        pros=["Повседневный формат"],
        cons=["Точная кухня требует проверки"],
        popularity_level="Низкая",
        data_completeness="Низкая",
    ),

    # ---- 10. Бары / nightlife / развлечения ----
    _v(
        "ALM-028", "Домашний", "Бар", "Local concept bar",
        ["Авторские напитки", "Local cuisine"], "mid", None,
        "Не найдено", "Не найдено",
        ["Вечер", "Локальный опыт", "Друзья"],
        ["Современное", "Камерная"],
        68, "Средняя",
        scenarios={"date": 3, "business": 1, "family": 1, "friends": 5,
                   "birthday": 2, "banquet": 1, "corporate": 1, "tourist": 4,
                   "laptop": 1, "large_group": 3},
        pros=["Международное признание (50 Best Discovery)", "Авторские напитки"],
        cons=["Малая вместимость"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-045", "Белый Слон", "Бар", "Bar / restaurant",
        ["Барная кухня"], "mid", None,
        "Не найдено", "Не найдено",
        ["Ночная жизнь", "Друзья"],
        ["Шумное", "Тусовочное"],
        73, "Низкая",
        scenarios={"date": 2, "business": 1, "family": 1, "friends": 5,
                   "birthday": 3, "banquet": 1, "corporate": 1, "tourist": 2,
                   "laptop": 0, "large_group": 3},
        pros=["Ночной формат"],
        cons=["График требует проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-046", "Harat's Republic", "Паб", "Irish pub",
        ["Европейская", "Pub food"], "mid", None,
        "Не найдено", "Не найдено",
        ["Друзья", "Спорт", "Live events"],
        ["Шумное", "Тусовочное"],
        72, "Средняя",
        live_music=True,
        scenarios={"date": 2, "business": 1, "family": 2, "friends": 5,
                   "birthday": 3, "banquet": 2, "corporate": 2, "tourist": 2,
                   "laptop": 1, "large_group": 5},
        pros=["Irish pub-формат", "Спортивные трансляции"],
        cons=["Поздний график требует проверки"],
        popularity_level="Высокая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-047", "Avenue Lounge & Karaoke", "Развлечения", "Karaoke / lounge",
        ["Европейская", "Bar food"], "upper_mid", 7500,
        "Не найдено", "ул. Мынбаева, 53, угол ул. Ауэзова",
        ["День рождения", "Private event"],
        ["Шумное", "Тусовочное"],
        71, "Низкая",
        wifi=True, vip_room=True, parking=True, free_parking=True,
        breakfast=True, business_lunch=True, booking_available=True,
        working_hours="Круглосуточно",
        capacity=163,
        phone="+7 701 979 79 21; +7 700 979 79 44",
        source_url="https://restoran.kz/pub/8256-avenue-lounge-karaoke",
        scenarios={"date": 3, "business": 2, "family": 3, "friends": 5,
                   "birthday": 5, "banquet": 4, "corporate": 4, "tourist": 2,
                   "laptop": 1, "large_group": 5},
        pros=["Караоке и танцпол", "4 VIP-кабинки", "Вместимость 163 места",
              "Круглосуточный режим", "Завтраки и business lunch"],
        cons=["Условия оплаты кабинок требуют проверки"],
        popularity_level="Средняя",
        data_completeness="Высокая",
    ),
    _v(
        "ALM-034", "Bellagio Restaurant & Club", "Ресторан", "Restaurant / club",
        ["Итальянская", "Европейская"], "premium", None,
        "Не найдено", "Не найдено",
        ["Вечер", "Банкет", "Private event"],
        ["Шумное", "Премиальная"],
        74, "Низкая",
        banquet_available=True,
        scenarios={"date": 4, "business": 3, "family": 2, "friends": 4,
                   "birthday": 4, "banquet": 4, "corporate": 4, "tourist": 2,
                   "laptop": 0, "large_group": 4},
        pros=["Club-формат", "Банкеты и private events"],
        cons=["Вместимость и депозит требуют проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-048", "Hopersbar", "Бар", "Bar",
        ["Bar food"], "mid", None,
        "Не найдено", "Не найдено",
        ["Вечер", "Друзья", "Nightlife"],
        ["Шумное", "Тусовочное"],
        70, "Низкая",
        scenarios={"date": 2, "business": 1, "family": 1, "friends": 5,
                   "birthday": 2, "banquet": 1, "corporate": 1, "tourist": 1,
                   "laptop": 0, "large_group": 3},
        pros=["Ночной формат", "Бронирование групп"],
        cons=["Данные требуют верификации"],
        popularity_level="Низкая",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-049", "Friends Bar & Terrace", "Бар", "Bar / terrace",
        ["Bar food"], "upper_mid", None,
        "Не найдено", "Не найдено",
        ["Друзья", "Терраса", "Вечер"],
        ["Тусовочное", "С террасой"],
        71, "Низкая",
        terrace=True,
        scenarios={"date": 3, "business": 1, "family": 2, "friends": 5,
                   "birthday": 3, "banquet": 1, "corporate": 1, "tourist": 2,
                   "laptop": 1, "large_group": 4},
        pros=["Терраса", "Вечерние встречи"],
        cons=["График требует проверки"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
    _v(
        "ALM-048B", "Dragonfly Izakaya", "Ресторан", "Japanese / izakaya",
        ["Японская"], "mid", None,
        "Не найдено", "Не найдено",
        ["Друзья", "Свидание", "Вечер"],
        ["Современное", "Камерная"],
        69, "Низкая",
        scenarios={"date": 4, "business": 2, "family": 3, "friends": 5,
                   "birthday": 3, "banquet": 1, "corporate": 1, "tourist": 3,
                   "laptop": 1, "large_group": 3},
        pros=["Положительные локальные отзывы", "Izakaya-формат"],
        cons=["Требует отдельной проверки карточки 2ГИС"],
        popularity_level="Средняя",
        data_completeness="Низкая",
    ),
]


import copy


def get_venues() -> list[dict[str, Any]]:
    """Вернуть список всех заведений (глубокая копия)."""
    return copy.deepcopy(VENUES)


def get_venue_by_id(venue_id: str) -> dict[str, Any] | None:
    """Найти заведение по venue_id."""
    for v in VENUES:
        if v["venue_id"] == venue_id:
            return dict(v)
    return None
